### ISSUE TITLE
1.12.2 Errors on MC startup, coming from BlockDrops?

### ISSUE THREAD

**Issue by jkroepke** [KidsDontPlay/Yunifier#10]
Hi.

on startup, I got tons of the error messages, if JEI BlockDrops is installed. https://minecraft.curseforge.com/projects/block-drops-jei-addon

```
[19:11:13] [pool-4-thread-50/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.world.BlockEvent$HarvestDropsEvent@52ea8db0:
java.lang.NullPointerException: null
	at mrriegel.instantunify.InstantUnify.replaceOptional(InstantUnify.java:159) ~[InstantUnify.class:?]
	at mrriegel.instantunify.InstantUnify.replace(InstantUnify.java:153) ~[InstantUnify.class:?]
	at java.util.ArrayList.replaceAll(ArrayList.java:1442) ~[?:1.8.0_144]
	at mrriegel.instantunify.InstantUnify.harvest(InstantUnify.java:114) ~[InstantUnify.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_221_InstantUnify_harvest_HarvestDropsEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179) ~[EventBus.class:?]
	at net.minecraftforge.event.ForgeEventFactory.fireBlockHarvesting(ForgeEventFactory.java:277) ~[ForgeEventFactory.class:?]
	at mrriegel.blockdrops.BlockDrops.getList(BlockDrops.java:232) ~[BlockDrops.class:?]
	at mrriegel.blockdrops.BlockDrops.lambda$getRecipes$7(BlockDrops.java:191) ~[BlockDrops.class:?]
	at mrriegel.blockdrops.BlockDrops.lambda$getRecipes$8(BlockDrops.java:202) ~[BlockDrops.class:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_144]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
```

**Comment by KidsDontPlay** [comment]
what version of instant unify, blockdrops and unidict do you use?
does it crash ingame without blockdrops?

**Comment by jkroepke** [comment]
```
ls | egrep -i 'unify|unidict|blockdrop|instant'
blockdrops-1.12.2-1.4.0.jar
instantunify-1.12.2-1.1.0.jar
UniDict-1.12.2-2.1.jar
```

This error appears only on mc startup and only if the cache of blockdrops is empty. There is no crash. But there are lot (tons!) message while blockdrops collecting the drops on client startup.

**Comment by KidsDontPlay** [comment]
I figured out what the problem is. Now I'm waiting for an answer from author of unidict
